[package]
name = "web3-gateway"
version = "0.3.0"
license = "GPL-3.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>", "Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
slog = "2.4.1"
parking_lot = "0.5"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
fdlimit = "0.1"
signal-hook = "0.1.8"
prometheus = { version = "0.8", features = ["push"] }
jsonrpc-core = { git = "https://github.com/oasislabs/jsonrpc.git", branch = "hyper-v0.12" }
jsonrpc-http-server = { git = "https://github.com/oasislabs/jsonrpc.git", branch = "hyper-v0.12" }
jsonrpc-ws-server = { git = "https://github.com/oasislabs/jsonrpc.git", branch = "hyper-v0.12" }
jsonrpc-macros = { git = "https://github.com/oasislabs/jsonrpc.git", branch = "hyper-v0.12" }
jsonrpc-pubsub = { git = "https://github.com/oasislabs/jsonrpc.git", branch = "hyper-v0.12" }
lazy_static = "1.3.0"
wasmi = "0.4"
ethcore = { git = "https://github.com/openethereum/openethereum", tag = "v3.0.1" }
common-types = { git = "https://github.com/openethereum/openethereum", tag = "v3.0.1" }
ethereum-types = "0.9.2" # ori 0.3.0
rlp = "0.4.0"
keccak-hash = "0.5.1"
#parity-reactor = { git = "https://github.com/oasislabs/oasis-parity", branch = "ekiden" }
parity-rpc = { git = "https://github.com/openethereum/openethereum", tag = "v3.0.1" }
#keccak-hash = { git = "https://github.com/oasislabs/oasis-parity", branch = "ekiden" }
#mem = { git = "https://github.com/oasislabs/oasis-parity", branch = "ekiden" }
parity-bytes = "0.1"

## Common functionality between runtime and gateway
oasis-ssvm-runtime-common = { path = "../common" }
oasis-ssvm-runtime-parity = { path = "../oasis-parity" }

## Oasis Core client dependencies.
oasis-core-client = { git = "https://github.com/oasisprotocol/oasis-core", tag = "v20.7" }
oasis-core-runtime = { git = "https://github.com/oasisprotocol/oasis-core", tag = "v20.7" }
oasis-core-keymanager-client = { git = "https://github.com/oasisprotocol/oasis-core", tag = "v20.7" }
oasis-ssvm-runtime-api = { path = "../api" }

clap = "2.29.1"
rand = "0.4"
grpcio = { version = "0.4.4", features = ["openssl"] }
tokio = "0.1.17"
tokio-threadpool = "0.1.14"
failure = "0.1.5"
io-context = "0.2.0"

[build-dependencies]
rustc_version = "0.2"

[dev-dependencies]
hex = "0.3"

[features]
default = ["pubsub"]
pubsub = []
production-genesis = ["oasis-ssvm-runtime-common/production-genesis"]
benchmarking = ["oasis-ssvm-runtime-common/benchmarking"]

[[bin]]
name = "gateway"
path ="bin/main.rs"