[package]
name = "oasis-ssvm-runtime-parity"
version = "0.3.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]

[dependencies]


[features]
default = []
benchmarking = []
production-genesis = []
test = []

